server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reserve
          uri: http://localhost:8082
          predicates:
            - Path=/reserves/**, 
        - id: machine
          uri: http://localhost:8083
          predicates:
            - Path=/machines/**, 
        - id: court
          uri: http://localhost:8084
          predicates:
            - Path=/courts/**, 
        - id: mypage
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserves/**, 
        - id: machine
          uri: http://machine:8080
          predicates:
            - Path=/machines/**, 
        - id: court
          uri: http://court:8080
          predicates:
            - Path=/courts/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
